[theme]
# Primary accent color for widgets (buttons, sliders, etc.)
primaryColor = "#185FA5"

# Background color for the main page
backgroundColor = "#ffffffff"

# Background color for the sidebar and other elements
secondaryBackgroundColor = "#E6F1FB"

# Text color
textColor = "#042C53"

# Font family (choose "sans serif", "serif", or "monospace")
font = "monospace"
